# To do lottery, place a chest that is enchanted of "MENDING".
#
# NumberOfItems means how many items included the lottery.
#
# You should name as "Item~".(~ is int type number)
# Name is Items name
#
# Enchantment is Enchantment (If you use this parameter, you should write UPPERCASE)
#
# Enchantment_level is enchantments level
#
# Material is material name (You should write UPPERCASE)
#
# Restriction is enchantments levels parameter. (If you use this parameter, you should write UPPERCASE)
# if you write enchantment, you should write this parameter.(default is "Nothing")
#
# ItemFlag is some settings.(if you do not know this, do not touch this)
# If you write this parameter, you should write UPPERCASE
#
# Weight is probability of the item selected (double type number)
# number range is 0.001 ~ 0.999 (= 0.1% ~ 99.9%)
# (exp. 50% 's weight is 0.50 and 99% is 0.99)
#
# FanfareSound is the name of a sound that is played when the player picks up the item.
# (If you use fanfare, you should write FanfareSound with UPPERCASE. / default is Nothing)
# You can set one sound to one item.
#
# FanfareSoundVolume is fanfares volume.(default is 1F / float type number)
# When you do not use this, write 0.
#
# FanfareSoundPitch is fanfares pitch.(default is 1F / float type number)
# If you set the value of this parameter is 2, the sound becomes 2 times speed.
# When you do not use this, write 0.
#
# LoreUse is a parameter of lore use or not use.
# You should write true or false.(boolean type)
# When you do not set lore, you should write false, and you want to set lore, you should write true.
# If you write false in this parameter, you do not have to write "Lore"parameter.
#
# Lore is items descriptions.
# You should write like this.->'LoreLineNumber(int type number): "Lore"'
# exp.) 1: "this is first line of an item lore."
# You can set maximum 10 lines.
# You can use "§".(see here -> https://htmlcolorcodes.com/minecraft-color-codes/)
#
# You must write Name,Material,Weight (other parameters are options.)
# If you do not have parameters, write "Nothing"
#
# Details of configurations are here.(https://hub.spigotmc.org/javadocs/bukkit/)
#-----------------------------------------------------------------------------------
#
# MIT License
#
#Copyright (c) 2022 Sakaki-Aruka
#
#Permission is hereby granted, free of charge, to any person obtaining a copy
#of this software and associated documentation files (the "Software"), to deal
#in the Software without restriction, including without limitation the rights
#to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
#copies of the Software, and to permit persons to whom the Software is
#furnished to do so, subject to the following conditions:
#
#The above copyright notice and this permission notice shall be included in all
#copies or substantial portions of the Software.
#
#THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
#SOFTWARE.
#-----------------------------------------------------------------------------------

NumberOfItems: 3

Item1:
  Name: "First"
  Enchantment: "MENDING LUCK"
  Enchantment_level: "1 3"
  Material: "STONE"
  Restriction: "true true"
  ItemFlag: "Nothing"
  Weight: 0.50
  FanfareSound: "Nothing"
  FanfareSoundVolume: "0"
  FanfareSoundPitch: "0"
  LoreUse: false
  unbreak: false


Item2:
  Name: "Second"
  Enchantment: "LUCK"
  Enchantment_level: "2"
  Material: "SAND"
  Restriction: "true"
  ItemFlag: "HIDE_ENCHANTS"
  Weight: 0.25
  FanfareSound: "BLOCK_ANVIL_PLACE"
  FanfareSoundVolume: "1F"
  FanfareSoundPitch: "2F"
  LoreUse: true
  LoreLines: 10
  Lore:
    1: "§a1"
    2: "§b2"
    3: "§c3"
    4: "§d4"
    5: "§f5"
    6: "§g6"
    7: "§k7"
    8: "§l8"
    9: "§o9"
    10: "§f10"
  unbreak: false

# smallest settings
Item3:
  Name: "Third"
  Enchantment: "Nothing"
  Enchantment_level: "-1"
  Material: "ICE"
  Restriction: "Nothing"
  ItemFlag: "Nothing"
  Weight: 0.25
  FanfareSound: "Nothing"
  FanfareSoundVolume: "0"
  FanfareSoundPitch: "0"
  LoreUse: false
  unbreak: false